[package]
name = "if-let"
version = "0.1.0"
authors = ["Jascha <jascha@jaeh.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
